### PR TITLE
Apple TV support + automatic Framework search paths setting

### PR DESCRIPTION
**Pull request by rshev**
Correct SDK selection for Apple TV.
Automatic framework search paths setting to parent project build path (pods work out-of-the-box on Apple TV).

### CODE REVIEW

**Comment by johnno1962** [comment]
Hi Roman, I can’t merge this request at the moment as I wouldn’t set the default FRAMEWORK_SEARCH_PATH to ../** myself and don’t have the time for the retest this would require. I’ll leave this open so people can see what is required for Apple TV.

**Comment by rshev** [comment]
Hi, thanks for looking into it! `FRAMEWORK_SEARCH_PATH = "../**"` is just a placeholder in `pbxproj` file, it's overwritten by injection script with the build path for the correct SDK. Do you want me to leave it as it was and only override if sdk is definitely `appletv`?

**Comment by orta** [comment]
@johnno1962 - this probably wants another look 👍

**Comment by johnno1962** [comment]
Hi @orta, @rshev. In truth I had reservations about this PR as I thought it might slow injection down for large projects. There would need to be two changes If you could change the FRAMEWORK_SEARCH_PATHS placeholder of "../**” to “” that would be one fix but I am also concerned that a FRAMEWORK_SEARCH_PATHS of $buildRoot\/Products\/Debug-$sdk/** will bring in a very large number of directories for some projects which agan will slow things down. I’d merge it without hesitation if it were only the change to BundleInjection.h and the change:

+        if ( $learnt =~ /-(appletvsimulator)\// ) {
 +            $config =~ s/iphone/appletv/
 +        }

Framework search paths took and age to get working. I’d rather not tangle with it at this stage.

**Comment by rshev** [comment]
@johnno1962 No problem, made it. 
Do you mind if I leave FRAMEWORK_SEARCH_PATHS adjuster there commented out? I still need it for projects using CocoaPods, for both iOS and AppleTV. It just doesn't find frameworks without that and asks to adjust bundle project manually, so annoying.
Thanks!

**Comment by johnno1962** [comment]
It’s interesting you have frameworks requiring a $buildRoot\/Products\/Debug-$sdk\/\*\* search path. Where is the framework that can’t be found if you don’t do this?

**Comment by rshev** [comment]
Sorry, tried to make a basic test project for you, but can't reproduce the issue. 
It seems to be something weird with the project I'm actively working on.
Tried to delete `iOSInjectionProject` to force it to be rebuilt, but it doesn't help.
And Build Settings look almost identical in comparison. Bummer.

**Comment by johnno1962** [comment]
I’ve merged it as is. Any information you turn up about what’s going on with your problem project let me know. Thanks for wading through all that Perl!

**Comment by rshev** [comment]
Thanks a lot, I'm happy to contribute to such a great project as yours!

**Pull request merged**
